export type CategoryId =
  | "data"
  | "pipelines"
  | "ontology"
  | "search"
  | "security"
  | "interface"
  | "workflows"
  | "ai"
  | "operations";

export type LicenseGroup = "permissive" | "weak-copyleft" | "strong-copyleft";

export type Project = {
  id: string;
  name: string;
  description: string;
  category: CategoryId;
  license: string;
  licenseGroup: LicenseGroup;
  language: string;
  repository: string;
  analogue: string;
  tags: string[];
};

export const categories: Array<{ id: CategoryId; label: string }> = [
  { id: "data", label: "Data" },
  { id: "pipelines", label: "Pipelines" },
  { id: "ontology", label: "Ontology" },
  { id: "search", label: "Search" },
  { id: "security", label: "Security" },
  { id: "interface", label: "Interface" },
  { id: "workflows", label: "Workflows" },
  { id: "ai", label: "AI & models" },
  { id: "operations", label: "Operations" },
];

export const projects: Project[] = [
  {
    id: "postgresql",
    name: "PostgreSQL",
    description: "Reliable operational database for objects, actions, and audit records.",
    category: "data",
    license: "PostgreSQL",
    licenseGroup: "permissive",
    language: "C",
    repository: "https://github.com/postgres/postgres",
    analogue: "Foundry data layer",
    tags: ["relational", "transactions", "jsonb"],
  },
  {
    id: "postgis",
    name: "PostGIS",
    description: "Spatial types and queries for operational and geotemporal data.",
    category: "data",
    license: "GPL-2.0+",
    licenseGroup: "strong-copyleft",
    language: "C",
    repository: "https://github.com/postgis/postgis",
    analogue: "Gotham geospatial data",
    tags: ["geospatial", "postgresql", "gis"],
  },
  {
    id: "duckdb",
    name: "DuckDB",
    description: "Embedded analytical SQL engine for local files and Parquet.",
    category: "data",
    license: "MIT",
    licenseGroup: "permissive",
    language: "C++",
    repository: "https://github.com/duckdb/duckdb",
    analogue: "Foundry local analytics",
    tags: ["olap", "embedded", "parquet"],
  },
  {
    id: "iceberg",
    name: "Apache Iceberg",
    description: "Versioned lakehouse tables with snapshots and schema evolution.",
    category: "data",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Java",
    repository: "https://github.com/apache/iceberg",
    analogue: "Foundry datasets",
    tags: ["lakehouse", "tables", "snapshots"],
  },
  {
    id: "delta-lake",
    name: "Delta Lake",
    description: "ACID table framework for data lake and streaming workloads.",
    category: "data",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Scala",
    repository: "https://github.com/delta-io/delta",
    analogue: "Foundry datasets",
    tags: ["lakehouse", "acid", "spark"],
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    description: "Fast column-oriented database for real-time operational analytics.",
    category: "data",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "C++",
    repository: "https://github.com/ClickHouse/ClickHouse",
    analogue: "Contour analytics",
    tags: ["olap", "realtime", "columnar"],
  },
  {
    id: "trino",
    name: "Trino",
    description: "Distributed SQL across databases, object stores, and lakehouse tables.",
    category: "data",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Java",
    repository: "https://github.com/trinodb/trino",
    analogue: "Foundry federated query",
    tags: ["sql", "federation", "distributed"],
  },
  {
    id: "minio",
    name: "MinIO",
    description: "S3-compatible object storage for datasets and model artifacts.",
    category: "data",
    license: "AGPL-3.0",
    licenseGroup: "strong-copyleft",
    language: "Go",
    repository: "https://github.com/minio/minio",
    analogue: "Foundry object storage",
    tags: ["s3", "storage", "objects"],
  },
  {
    id: "kafka",
    name: "Apache Kafka",
    description: "Durable event backbone for streams, changes, and action events.",
    category: "pipelines",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Java",
    repository: "https://github.com/apache/kafka",
    analogue: "Foundry streaming",
    tags: ["events", "streaming", "messaging"],
  },
  {
    id: "flink",
    name: "Apache Flink",
    description: "Stateful processing for real-time and batch data pipelines.",
    category: "pipelines",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Java",
    repository: "https://github.com/apache/flink",
    analogue: "Pipeline Builder",
    tags: ["streaming", "stateful", "batch"],
  },
  {
    id: "debezium",
    name: "Debezium",
    description: "Change data capture for synchronizing operational systems.",
    category: "pipelines",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Java",
    repository: "https://github.com/debezium/debezium",
    analogue: "Foundry source sync",
    tags: ["cdc", "connectors", "events"],
  },
  {
    id: "dagster",
    name: "Dagster",
    description: "Asset-oriented orchestration with lineage and observability.",
    category: "pipelines",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Python",
    repository: "https://github.com/dagster-io/dagster",
    analogue: "Foundry pipelines",
    tags: ["orchestration", "assets", "lineage"],
  },
  {
    id: "airflow",
    name: "Apache Airflow",
    description: "Programmatic scheduling and monitoring for batch workflows.",
    category: "pipelines",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Python",
    repository: "https://github.com/apache/airflow",
    analogue: "Foundry pipelines",
    tags: ["scheduler", "dag", "batch"],
  },
  {
    id: "dbt-core",
    name: "dbt Core",
    description: "SQL transformation, testing, documentation, and dependencies.",
    category: "pipelines",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Python",
    repository: "https://github.com/dbt-labs/dbt-core",
    analogue: "Foundry transforms",
    tags: ["sql", "transforms", "testing"],
  },
  {
    id: "openmetadata",
    name: "OpenMetadata",
    description: "Catalog, lineage, quality, governance, and business semantics.",
    category: "pipelines",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "TypeScript / Java",
    repository: "https://github.com/open-metadata/OpenMetadata",
    analogue: "Foundry catalog & lineage",
    tags: ["catalog", "lineage", "governance"],
  },
  {
    id: "datahub",
    name: "DataHub",
    description: "Metadata graph for discovering and governing data assets.",
    category: "pipelines",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Java / TypeScript",
    repository: "https://github.com/datahub-project/datahub",
    analogue: "Foundry catalog & lineage",
    tags: ["metadata", "catalog", "lineage"],
  },
  {
    id: "openlineage",
    name: "OpenLineage",
    description: "Open standard and integrations for lineage event collection.",
    category: "pipelines",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Java / Python",
    repository: "https://github.com/OpenLineage/OpenLineage",
    analogue: "Data Lineage",
    tags: ["standard", "lineage", "metadata"],
  },
  {
    id: "typedb",
    name: "TypeDB",
    description: "Strongly typed conceptual database with relations and inference.",
    category: "ontology",
    license: "MPL-2.0",
    licenseGroup: "weak-copyleft",
    language: "Rust",
    repository: "https://github.com/typedb/typedb",
    analogue: "Ontology object model",
    tags: ["types", "relations", "inference"],
  },
  {
    id: "apache-age",
    name: "Apache AGE",
    description: "Property graph and Cypher queries inside PostgreSQL.",
    category: "ontology",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "C",
    repository: "https://github.com/apache/age",
    analogue: "Ontology links",
    tags: ["graph", "cypher", "postgresql"],
  },
  {
    id: "neo4j",
    name: "Neo4j Community",
    description: "Mature graph database with the Cypher query language.",
    category: "ontology",
    license: "GPL-3.0",
    licenseGroup: "strong-copyleft",
    language: "Java",
    repository: "https://github.com/neo4j/neo4j",
    analogue: "Ontology links",
    tags: ["graph", "cypher", "relationships"],
  },
  {
    id: "jena",
    name: "Apache Jena",
    description: "RDF, OWL, SPARQL, and semantic reasoning toolkit.",
    category: "ontology",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Java",
    repository: "https://github.com/apache/jena",
    analogue: "Ontology semantics",
    tags: ["rdf", "sparql", "semantics"],
  },
  {
    id: "ontop",
    name: "Ontop",
    description: "Expose relational data as a virtual RDF knowledge graph.",
    category: "ontology",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Java",
    repository: "https://github.com/ontop/ontop",
    analogue: "Ontology federation",
    tags: ["rdf", "virtual-graph", "sparql"],
  },
  {
    id: "opensearch",
    name: "OpenSearch",
    description: "Distributed search and analytics for objects, documents, and logs.",
    category: "search",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Java",
    repository: "https://github.com/opensearch-project/OpenSearch",
    analogue: "Object Explorer search",
    tags: ["search", "documents", "analytics"],
  },
  {
    id: "qdrant",
    name: "Qdrant",
    description: "Vector and hybrid search for semantic object retrieval.",
    category: "search",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Rust",
    repository: "https://github.com/qdrant/qdrant",
    analogue: "AIP semantic search",
    tags: ["vectors", "semantic", "hybrid-search"],
  },
  {
    id: "keycloak",
    name: "Keycloak",
    description: "Identity, SSO, OIDC, SAML, users, and groups.",
    category: "security",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Java",
    repository: "https://github.com/keycloak/keycloak",
    analogue: "Platform identity",
    tags: ["identity", "oidc", "sso"],
  },
  {
    id: "spicedb",
    name: "SpiceDB",
    description: "Zanzibar-inspired relationship-based authorization database.",
    category: "security",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Go",
    repository: "https://github.com/authzed/spicedb",
    analogue: "Ontology permissions",
    tags: ["authorization", "rebac", "permissions"],
  },
  {
    id: "openfga",
    name: "OpenFGA",
    description: "Fine-grained authorization modeled through object relations.",
    category: "security",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Go",
    repository: "https://github.com/openfga/openfga",
    analogue: "Ontology permissions",
    tags: ["authorization", "fga", "relations"],
  },
  {
    id: "opa",
    name: "Open Policy Agent",
    description: "General-purpose policy engine for contextual access and governance.",
    category: "security",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Go",
    repository: "https://github.com/open-policy-agent/opa",
    analogue: "Dynamic security",
    tags: ["policy", "abac", "governance"],
  },
  {
    id: "blueprint",
    name: "Blueprint",
    description: "Palantir's React toolkit for dense desktop web interfaces.",
    category: "interface",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "TypeScript",
    repository: "https://github.com/palantir/blueprint",
    analogue: "Foundry interface",
    tags: ["react", "components", "desktop"],
  },
  {
    id: "base-ui",
    name: "Base UI",
    description: "Unstyled, accessible React primitives for custom design systems.",
    category: "interface",
    license: "MIT",
    licenseGroup: "permissive",
    language: "TypeScript",
    repository: "https://github.com/mui/base-ui",
    analogue: "Application primitives",
    tags: ["react", "accessible", "unstyled"],
  },
  {
    id: "maplibre",
    name: "MapLibre GL JS",
    description: "Interactive vector-tile maps for geospatial applications.",
    category: "interface",
    license: "BSD-3-Clause",
    licenseGroup: "permissive",
    language: "TypeScript",
    repository: "https://github.com/maplibre/maplibre-gl-js",
    analogue: "Gotham map",
    tags: ["maps", "vector-tiles", "webgl"],
  },
  {
    id: "deckgl",
    name: "deck.gl",
    description: "GPU-powered visualization layers for large geospatial datasets.",
    category: "interface",
    license: "MIT",
    licenseGroup: "permissive",
    language: "TypeScript",
    repository: "https://github.com/visgl/deck.gl",
    analogue: "Gotham map layers",
    tags: ["geospatial", "gpu", "visualization"],
  },
  {
    id: "cesium",
    name: "CesiumJS",
    description: "3D globes, terrain, imagery, and streamed 3D geospatial data.",
    category: "interface",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "JavaScript",
    repository: "https://github.com/CesiumGS/cesium",
    analogue: "Gotham 3D map",
    tags: ["3d", "globe", "terrain"],
  },
  {
    id: "cytoscape",
    name: "Cytoscape.js",
    description: "Interactive graph analysis and relationship visualization.",
    category: "interface",
    license: "MIT",
    licenseGroup: "permissive",
    language: "JavaScript",
    repository: "https://github.com/cytoscape/cytoscape.js",
    analogue: "Object Explorer graph",
    tags: ["graphs", "networks", "visualization"],
  },
  {
    id: "echarts",
    name: "Apache ECharts",
    description: "Flexible charts and dashboards for analytical applications.",
    category: "interface",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "TypeScript",
    repository: "https://github.com/apache/echarts",
    analogue: "Quiver & Contour",
    tags: ["charts", "dashboard", "visualization"],
  },
  {
    id: "tanstack-table",
    name: "TanStack Table",
    description: "Headless tables and data grids with complete visual control.",
    category: "interface",
    license: "MIT",
    licenseGroup: "permissive",
    language: "TypeScript",
    repository: "https://github.com/TanStack/table",
    analogue: "Foundry object tables",
    tags: ["tables", "headless", "react"],
  },
  {
    id: "appsmith",
    name: "Appsmith",
    description: "Low-code internal tools, operational apps, and dashboards.",
    category: "workflows",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "TypeScript / Java",
    repository: "https://github.com/appsmithorg/appsmith",
    analogue: "Workshop",
    tags: ["low-code", "internal-tools", "apps"],
  },
  {
    id: "streamlit",
    name: "Streamlit",
    description: "Fast Python data applications and analytical prototypes.",
    category: "workflows",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Python",
    repository: "https://github.com/streamlit/streamlit",
    analogue: "Code Workbook apps",
    tags: ["python", "data-apps", "prototype"],
  },
  {
    id: "superset",
    name: "Apache Superset",
    description: "Self-service business intelligence and visual analytics.",
    category: "workflows",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Python / TypeScript",
    repository: "https://github.com/apache/superset",
    analogue: "Contour",
    tags: ["bi", "dashboards", "sql"],
  },
  {
    id: "temporal",
    name: "Temporal",
    description: "Durable execution for long-running actions and workflows.",
    category: "workflows",
    license: "MIT",
    licenseGroup: "permissive",
    language: "Go",
    repository: "https://github.com/temporalio/temporal",
    analogue: "Ontology Actions",
    tags: ["workflows", "durable", "actions"],
  },
  {
    id: "node-red",
    name: "Node-RED",
    description: "Visual event flows, integrations, and operational automation.",
    category: "workflows",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "JavaScript",
    repository: "https://github.com/node-red/node-red",
    analogue: "Automate",
    tags: ["automation", "flows", "integrations"],
  },
  {
    id: "great-expectations",
    name: "Great Expectations",
    description: "Declarative data quality tests, validation, and documentation.",
    category: "workflows",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Python",
    repository: "https://github.com/great-expectations/great_expectations",
    analogue: "Data Health",
    tags: ["quality", "validation", "tests"],
  },
  {
    id: "langgraph",
    name: "LangGraph",
    description: "Stateful agents with controllable execution and human review.",
    category: "ai",
    license: "MIT",
    licenseGroup: "permissive",
    language: "Python / TypeScript",
    repository: "https://github.com/langchain-ai/langgraph",
    analogue: "AIP agents",
    tags: ["agents", "llm", "human-in-loop"],
  },
  {
    id: "mlflow",
    name: "MLflow",
    description: "Experiments, models, prompts, evaluations, and registry.",
    category: "ai",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Python / TypeScript",
    repository: "https://github.com/mlflow/mlflow",
    analogue: "AIP model management",
    tags: ["mlops", "registry", "evaluation"],
  },
  {
    id: "feast",
    name: "Feast",
    description: "Feature storage for model training and online inference.",
    category: "ai",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Python",
    repository: "https://github.com/feast-dev/feast",
    analogue: "AIP feature layer",
    tags: ["features", "training", "inference"],
  },
  {
    id: "bentoml",
    name: "BentoML",
    description: "Package and serve models, AI APIs, and inference jobs.",
    category: "ai",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Python",
    repository: "https://github.com/bentoml/BentoML",
    analogue: "AIP model serving",
    tags: ["serving", "inference", "apis"],
  },
  {
    id: "kserve",
    name: "KServe",
    description: "Autoscaled predictive and generative inference on Kubernetes.",
    category: "ai",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Go / Python",
    repository: "https://github.com/kserve/kserve",
    analogue: "AIP deployments",
    tags: ["kubernetes", "inference", "autoscaling"],
  },
  {
    id: "vllm",
    name: "vLLM",
    description: "High-throughput OpenAI-compatible LLM inference server.",
    category: "ai",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Python",
    repository: "https://github.com/vllm-project/vllm",
    analogue: "AIP language models",
    tags: ["llm", "inference", "serving"],
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    description: "Container orchestration foundation for cloud and edge runtimes.",
    category: "operations",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Go",
    repository: "https://github.com/kubernetes/kubernetes",
    analogue: "Apollo runtime",
    tags: ["containers", "orchestration", "cloud"],
  },
  {
    id: "helm",
    name: "Helm",
    description: "Versioned application packages for Kubernetes deployments.",
    category: "operations",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Go",
    repository: "https://github.com/helm/helm",
    analogue: "Apollo products",
    tags: ["kubernetes", "packages", "deployment"],
  },
  {
    id: "argo-cd",
    name: "Argo CD",
    description: "Declarative GitOps deployments, health checks, and rollbacks.",
    category: "operations",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Go",
    repository: "https://github.com/argoproj/argo-cd",
    analogue: "Apollo continuous delivery",
    tags: ["gitops", "deployment", "rollback"],
  },
  {
    id: "opentelemetry",
    name: "OpenTelemetry",
    description: "Vendor-neutral telemetry collection for traces, metrics, and logs.",
    category: "operations",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Go",
    repository: "https://github.com/open-telemetry/opentelemetry-collector",
    analogue: "Apollo observability",
    tags: ["telemetry", "traces", "metrics"],
  },
  {
    id: "prometheus",
    name: "Prometheus",
    description: "Metrics, alerting, and service-level health evaluation.",
    category: "operations",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Go",
    repository: "https://github.com/prometheus/prometheus",
    analogue: "Apollo health",
    tags: ["metrics", "alerting", "slo"],
  },
  {
    id: "grafana",
    name: "Grafana",
    description: "Operational dashboards for metrics, logs, and traces.",
    category: "operations",
    license: "AGPL-3.0",
    licenseGroup: "strong-copyleft",
    language: "TypeScript / Go",
    repository: "https://github.com/grafana/grafana",
    analogue: "Apollo operations UI",
    tags: ["dashboards", "observability", "monitoring"],
  },
  {
    id: "trivy",
    name: "Trivy",
    description: "Vulnerability, configuration, secret, and SBOM scanning.",
    category: "operations",
    license: "Apache-2.0",
    licenseGroup: "permissive",
    language: "Go",
    repository: "https://github.com/aquasecurity/trivy",
    analogue: "Apollo security",
    tags: ["security", "sbom", "vulnerabilities"],
  },
];

export const recipes: Array<{
  id: string;
  name: string;
  description: string;
  projectIds: string[];
}> = [
  {
    id: "solo",
    name: "Solo prototype",
    description: "A compact local-first foundation for one builder.",
    projectIds: [
      "postgresql",
      "duckdb",
      "dagster",
      "apache-age",
      "keycloak",
      "spicedb",
      "blueprint",
      "maplibre",
      "cytoscape",
      "temporal",
    ],
  },
  {
    id: "foundry",
    name: "Foundry-like",
    description: "Data integration, ontology, governance, and operational apps.",
    projectIds: [
      "postgresql",
      "iceberg",
      "trino",
      "dagster",
      "dbt-core",
      "openmetadata",
      "typedb",
      "opensearch",
      "keycloak",
      "spicedb",
      "opa",
      "blueprint",
      "echarts",
      "temporal",
    ],
  },
  {
    id: "gotham",
    name: "Gotham-like",
    description: "Geospatial investigation, relationship analysis, and secure actions.",
    projectIds: [
      "postgresql",
      "postgis",
      "opensearch",
      "keycloak",
      "spicedb",
      "maplibre",
      "deckgl",
      "cytoscape",
      "temporal",
    ],
  },
  {
    id: "aip",
    name: "AIP-like",
    description: "Agents, model lifecycle, retrieval, and scalable inference.",
    projectIds: [
      "postgresql",
      "qdrant",
      "langgraph",
      "mlflow",
      "feast",
      "bentoml",
      "kserve",
      "vllm",
      "kubernetes",
      "opentelemetry",
    ],
  },
  {
    id: "apollo",
    name: "Apollo-like",
    description: "GitOps delivery, telemetry, health checks, and security scanning.",
    projectIds: [
      "kubernetes",
      "helm",
      "argo-cd",
      "opentelemetry",
      "prometheus",
      "grafana",
      "trivy",
    ],
  },
];
